//统一封装返回
module.exports = {
	ZK_INVESTMENT: require('./ZK_INVESTMENT'),
	ZK_PARAMINFO: require('./ZK_PARAMINFO'),
	ZK_PERMITCONFIG: require('./ZK_PERMITCONFIG'),
	ZK_PERMITINFO: require('./ZK_PERMITINFO'),
	ZK_ROLEINFO: require('./ZK_ROLEINFO'),
	ZK_USERINFO: require('./ZK_USERINFO'),
	ZK_INVESTOR: require('./ZK_INVESTOR'),
	ZK_INVESTOR_CASE: require('./ZK_INVESTOR_CASE'),
	ZK_INVESTOR_TEAM: require('./ZK_INVESTOR_TEAM'),
	ZK_NAVTREE: require('./ZK_NAVTREE'),
	ZK_INFORMATION: require('./ZK_INFORMATION'),
};
